name: test

on:
  pull_request_review:
    types: [submitted]
    branches: ['master']

jobs:
  test-usage:
    if: ${{ github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.review.commit_id }}

      - name: Notarize and verify PR
        uses: docker://codenotary/notarize-and-verify-pr:latest
        with:
          # Args are (in this order):
          # - CNIL REST API base URL (e.g. https://<host>:<port>/api/v1)
          # - CNIL REST API personal token
          # - CNIL gRPC host
          # - CNIL gRPC port
          # - CNIL ledger ID
          # - comma-separated list of required PR approvers (GitHub usernames)
          # - GitHub username (signer ID) of the current PR approver
          # NOTE: to get the args from secrets use the following syntax:
          #       ${{ secrets.SOME_SECRET_NAME }}
          args: >
            ${{ secrets.CNIL_REST_API_URL }}
            ${{ secrets.CNIL_PERSONAL_TOKEN }}
            ${{ secrets.CNIL_GRPC_HOST }}
            ${{ secrets.CNIL_GRPC_PORT }}
            ${{ secrets.CNIL_LEDGER_ID }}
            dmacvicar,padurean-alt
            ${{ github.event.review.user.login }}
