name: test

on:
  pull_request_review:
    types: [submitted]
    branches: [main, test-action]

jobs:
  test-usage:
    if: ${{ github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.review.commit_id }}

      - name: Notarize and verify PR
        uses: codenotary/notarize-and-verify-pr-action@v2.0.0
        # uses: codenotary/notarize-and-verify-pr-action@main
        with:
          cnil_host: ${{ secrets.CNIL_HOST }}
          # if this input is ommitted, default port 443 will be used:
          cnil_grpc_port: 33443
          current_pr_approver: ${{ github.event.review.user.login }}
          cnil_api_keys: ${{ secrets.CNIL_API_KEYS }}

          # if this input is ommitted, default port 443 will be used:
          # cnil_http_port: 33443

          # if the cnil_api_keys input (above) is omitted, then the following 3 inputs are required:
          # cnil_personal_token: ${{ secrets.CNIL_PERSONAL_TOKEN }}
          # cnil_ledger: ${{ secrets.CNIL_LEDGER_ID }}
          # required_pr_approvers: mmeloni,padurean-alt
